name: workflow
on:
  push:
    branches:
      - master
      
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Instalar dependências
        run: npm install

      - name: Install snyk
        run: npm install -g snyk

      - name: Configure Snyk endpoint
        run: snyk config set endpoint=https://api.us.snyk.io

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
     
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - name: Configure Snyk endpoint
        run: snyk config set endpoint=https://api.us.snyk.io
      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: npm install
        run: npm install
      - name: Snyk Test
        continue-on-error: true
        run: snyk test 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
